---
- hosts: localhost

  tasks:

    - name: check if webserver is running
      command: docker ps
      register: dockerps

    - name: debug
      debug:
        var: dockerps
        verbosity: 1

    - name: stop running container

      block:
        - name: stop apache2 container
          command: docker stop hello-apache2-server1

        - name: remove apache2 container
          command: docker rm hello-apache2-server1

      when: '"apache2-server1" in dockerps.stdout'

    - name: remove apache2 image before rebuilding
      community.docker.docker_image:
        name: hello-apache2
        state: absent

    - name: Build apache2 image
      community.docker.docker_image:
        build:
          path: ../files/docker/
        name: hello-apache2
        source: build
        state: present

    - name: "Run docker-compose up -d"
      command: docker-compose up -d
      args:
        chdir: ../files/docker/
